### ISSUE TITLE
Badges displayed in the wrong position

### ISSUE THREAD

**Issue by Stockless** [JuliaHealth/KomaMRI.jl#551]
The badges in the documentation should be next to the packages table, but they are centered.

**Comment by cncastillo** [comment]
The solution is to literally change the `center-images.css` to this:

```css
img:not(a img) {
  display: block;
  margin-left: auto;
  margin-right: auto;
}
```
